basePath: /api
definitions:
  model.Food:
    properties:
      carbohydrate_g:
        type: number
      energy_kcal:
        type: number
      fat_g:
        type: number
      fiber_g:
        type: number
      id:
        type: string
      name:
        type: string
      protein_g:
        type: number
      source:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API para o MVP do SaaS para nutricionistas.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API SaaS Nutri
  version: "1.0"
paths:
  /foods:
    get:
      consumes:
      - application/json
      description: Busca alimentos na base de dados (mock/API externa) com base em
        um termo de pesquisa.
      parameters:
      - description: Termo para buscar o alimento
        example: maçã
        in: query
        name: search
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de alimentos encontrados
          schema:
            items:
              $ref: '#/definitions/model.Food'
            type: array
        "400":
          description: Erro pela falta do parâmetro 'search'
          schema:
            type: string
        "500":
          description: Erro interno ao buscar os alimentos
          schema:
            type: string
      summary: Busca alimentos
      tags:
      - alimentos
swagger: "2.0"
