basePath: /api
definitions:
  client.MeasureItem:
    properties:
      display_name:
        type: string
      gram_equivalent:
        type: number
      measure_name:
        type: string
    type: object
  model.Food:
    properties:
      carbohydrate_g:
        type: number
      energy_kcal:
        type: number
      fat_g:
        type: number
      fiber_g:
        type: number
      id:
        type: string
      name:
        type: string
      protein_g:
        type: number
      source:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API para o MVP do SaaS para nutricionistas.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API SaaS Nutri
  version: "1.0"
paths:
  /foods:
    get:
      consumes:
      - application/json
      description: Busca alimentos na base TACO (via DynamoDB) com base em um termo
        de pesquisa.
      parameters:
      - description: Termo para buscar o alimento
        example: arroz
        in: query
        name: search
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de alimentos encontrados da TACO" // <--- REVERTIDO para
            model.Food
          schema:
            items:
              $ref: '#/definitions/model.Food'
            type: array
        "400":
          description: 'Erro: Parâmetro ''search'' é obrigatório'
          schema:
            type: string
        "500":
          description: Erro interno ao buscar dados dos alimentos
          schema:
            type: string
      summary: Busca alimentos (APENAS TACO/DynamoDB)
      tags:
      - alimentos
  /foods/{foodId}/measures:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de medidas caseiras e seus equivalentes em gramas
        para um ID de alimento específico.
      parameters:
      - description: 'ID do Alimento (ex: UUID ou código TACO)'
        example: d5e1c1b0-...
        in: path
        name: foodId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de medidas caseiras" // <--- REVERTIDO para client.MeasureItem
          schema:
            items:
              $ref: '#/definitions/client.MeasureItem'
            type: array
        "400":
          description: 'Erro: ID do alimento é obrigatório'
          schema:
            type: string
        "500":
          description: Erro interno ao buscar medidas
          schema:
            type: string
      summary: Busca medidas caseiras de um alimento
      tags:
      - alimentos
swagger: "2.0"
